import { Application } from "@hotwired/stimulus";
import AttachmentsController from "./controllers/attachments-controller";
import AuthenticateController from "./controllers/authenticate-controller";
import BadgeController from "./controllers/badge-controller";
import CheckboxController from "./controllers/checkbox-controller";
import EditorController from "./controllers/editor-controller";
import EmbedController from "./controllers/embed-controller";
import FilePickerController from "./controllers/file-picker-controller";
import FormController from "./controllers/form-controller";
import LinkController from "./controllers/link-controller";
import MeetingsController from "./controllers/meetings-controller";
import MessageController from "./controllers/message-controller";
import MessageToastController from "./controllers/message-toast-controller";
import MessengerController from "./controllers/messenger-controller";
import PaginationController from "./controllers/pagination-controller";
import PollsController from "./controllers/polls-controller";
import PresenceController from "./controllers/presence-controller";
import ReadByController from "./controllers/readby-controller";
import ScrollController from "./controllers/scroll-controller";
import SearchController from "./controllers/search-controller";
import SheetController from "./controllers/sheet-controller";
import SortController from "./controllers/sort-controller";
import TypingController from "./controllers/typing-controller";
import 'bootstrap/js/dist/dropdown';

const application = Application.start();
application.register("attachments", AttachmentsController);
application.register("authenticate", AuthenticateController);
application.register("badge", BadgeController);
application.register("checkbox", CheckboxController);
application.register("editor", EditorController);
application.register("embed", EmbedController);
application.register("file-picker", FilePickerController);
application.register("form", FormController);
application.register("link", LinkController);
application.register("meetings", MeetingsController);
application.register("message", MessageController);
application.register("message-toast", MessageToastController);
application.register("messenger", MessengerController);
application.register("pagination", PaginationController);
application.register("polls", PollsController);
application.register("presence", PresenceController);
application.register("readby", ReadByController);
application.register("scroll", ScrollController);
application.register("search", SearchController);
application.register("sheet", SheetController);
application.register("sort", SortController);
application.register("typing", TypingController);


