import { Application } from "@hotwired/stimulus";
import AttachmentsController from "./controllers/attachments-controller";
import CommentController from "./controllers/comment-controller";
import EditorController from "./controllers/editor-controller";
import EmbedController from "./controllers/embed-controller";
import EmbedHtmlController from "../js/controllers/embed-html-controller";
import FilePickerController from "./controllers/file-picker-controller";
import ImageController from "../js/controllers/image-controller";
import MediaController from "../js/controllers/media-controller";
import MeetingsController from "./controllers/meetings-controller";
import ModalController from "./controllers/modal-controller";
import PdfController from "../js/controllers/pdf-controller";
import PollsController from "./controllers/polls-controller";
import PresenceController from "./controllers/presence-controller";
import SidebarController from "./controllers/sidebar-controller";
import TabsController from "./controllers/tabs-controller";
import VersionController from "./controllers/version-controller";
import SheetController from "./controllers/sheet-controller";
import 'bootstrap/js/dist/dropdown';

const application = Application.start();
application.register("attachments", AttachmentsController);
application.register("comment", CommentController);
application.register("editor", EditorController);
application.register("embed", EmbedController);
application.register("embed-html", EmbedHtmlController);
application.register("file-picker", FilePickerController);
application.register("image", ImageController);
application.register("media", MediaController);
application.register("meetings", MeetingsController);
application.register("modal", ModalController);
application.register("pdf", PdfController);
application.register("polls", PollsController);
application.register("presence", PresenceController);
application.register("sidebar", SidebarController);
application.register("tabs", TabsController);
application.register("version", VersionController);
application.register("sheet", SheetController);
